; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=ia16-unknown-none-elf < %s | FileCheck %s
; RUN: llc -mtriple=ia16-unknown-none-elf -filetype=obj < %s -o %t
; RUN: llvm-readobj -r %t | FileCheck %s --check-prefix=RELOC

define i16 @constant() {
; CHECK-LABEL: constant:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movw $1, %ax
; CHECK-NEXT:    retw
  ret i16 1
}

define i16 @add(i16 %a, i16 %b) {
; CHECK-LABEL: add:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushw %bp
; CHECK-NEXT:    movw %sp, %bp
; CHECK-NEXT:    movw 6(%bp), %cx
; CHECK-NEXT:    movw 4(%bp), %ax
; CHECK-NEXT:    addw %cx, %ax
; CHECK-NEXT:    popw %bp
; CHECK-NEXT:    retw
  %sum = add i16 %a, %b
  ret i16 %sum
}

declare i16 @callee(i16, i16)

define i16 @caller() {
; CHECK-LABEL: caller:
; CHECK:       movw $3, %ax
; CHECK-NEXT:  pushw %ax
; CHECK-NEXT:  movw $2, %ax
; CHECK-NEXT:  pushw %ax
; CHECK-NEXT:  callw callee
; CHECK:       addw $4,
; CHECK:       retw
; RELOC:       R_386_PC16 callee
  %result = call i16 @callee(i16 2, i16 3)
  ret i16 %result
}

define i16 @signed_max(i16 %a, i16 %b) {
; CHECK-LABEL: signed_max:
; CHECK:       cmpw
; CHECK-NEXT:  jg
; CHECK:       jmp
; CHECK:       retw
entry:
  %greater = icmp sgt i16 %a, %b
  br i1 %greater, label %take_a, label %take_b

take_a:
  br label %done

take_b:
  br label %done

done:
  %result = phi i16 [ %a, %take_a ], [ %b, %take_b ]
  ret i16 %result
}

define i16 @shift_left_three(i16 %value) {
; CHECK-LABEL: shift_left_three:
; CHECK:       shlw %ax
; CHECK-NEXT:  shlw %ax
; CHECK-NEXT:  shlw %ax
; CHECK-NOT:   shlw $3
; CHECK:       retw
  %result = shl i16 %value, 3
  ret i16 %result
}

define i8 @byte_identity(i8 %value) {
; CHECK-LABEL: byte_identity:
; CHECK:       movb 4(%bp), %al
; CHECK:       retw
  ret i8 %value
}
