; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=ia16-unknown-none-elf < %s | FileCheck %s

define i16 @constant() {
; CHECK-LABEL: constant:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movw $1, %ax
; CHECK-NEXT:    retw
  ret i16 1
}

define i16 @add(i16 %a, i16 %b) {
; CHECK-LABEL: add:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushw %bp
; CHECK-NEXT:    movw %sp, %bp
; CHECK-NEXT:    movw 6(%bp), %cx
; CHECK-NEXT:    movw 4(%bp), %ax
; CHECK-NEXT:    addw %cx, %ax
; CHECK-NEXT:    popw %bp
; CHECK-NEXT:    retw
  %sum = add i16 %a, %b
  ret i16 %sum
}
